INSERT INTO PriceFeatures ( price_id, description) VALUES
(1, "One-pager"),
(1, "Stilren og lækker hjemmeside"),
(1, "Unikt design"),
(1, "Optimeret til Mobil & Tablet"),
(1, "Grundlæggende tekstskrivning"),
(1, "SEO (Søgemaskineoptimeret)"),
(1, "Kontaktformular"),
(1, "Første udkast klar på 7 arbejdsdage"),

(2, "Op til 6 sider (1 forside + 5 undersider)"),
(2, "Stilren og lækker hjemmeside"),
(2, "Unikt design"),
(2, "Optimeret til Mobil & Tablet"),
(2, "Grundlæggende tekstskrivning"),
(2, "SEO (Søgemaskineoptimeret)"),
(2, "Kontaktformular"),
(2, "Første udkast klar på 7 arbejdsdage"),

(3, "Op til 10 sider (1 forside + 9 undersider)"),
(3, "Stilren og lækker hjemmeside"),
(3, "Unikt design"),
(3, "Optimeret til Mobil & Tablet"),
(3, "Grundlæggende tekstskrivning"),
(3, "SEO (Søgemaskineoptimeret)"),
(3, "Udvidet kontaktformular"),
(3, "Salgsoptimeret"),
(3, "Hastighedsoptimeret"),
(3, "3 mdr. service inkluderet (værdi 2.985 kr. ekskl. moms"),
(3, "Første udkast klar på 7 arbejdsdage"),

(4, "Pakken tilpasses dine behov og krav"),
(4, "Mulighed for specialudviklede funktioner"),
(4, "Fokus på din forretning og målgruppe"),
(4, "Fuld fleksibilitet i design og funktionalitet");